// Fake data for pet sitters (50 records)
// Updated with Trust Badge System + Confidence Score
const sittersData = [
  {
    id: 1,
    name: "Đỗ Tùng",
    type: "Căn hộ",
    price: 150000,
    rating: 4.5,
    reviewCount: 312,
    location: "Hải Châu, Đà Nẵng",
    status: "Hiện đang giữ 1 mèo",
    amenities: ["Điều Hòa", "Đồ ăn thưởng miễn phí"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 312,
      liveUpdates: true,
    },
    confidenceScore: 92,
  },
  {
    id: 2,
    name: "Minh Nhật",
    type: "Nhà riêng",
    price: 200000,
    rating: 5.0,
    reviewCount: 1310,
    location: "Thanh Khê, Đà Nẵng",
    status: "Hiện đang giữ 3 mèo",
    amenities: ["Điều Hòa", "Máy lọc không khí", "Đồ chơi miễn phí"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 1310,
      liveUpdates: true,
    },
    confidenceScore: 98,
  },
  {
    id: 3,
    name: "Cat Moon Hotel",
    type: "Khách sạn thú cưng",
    price: 175000,
    rating: 5.0,
    reviewCount: 301,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 5 mèo",
    amenities: ["Vệ sinh miễn phí", "Tư vấn chế độ ăn"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 301,
      liveUpdates: true,
    },
    confidenceScore: 95,
  },
  {
    id: 4,
    name: "Phương Anh",
    type: "Căn hộ",
    price: 120000,
    rating: 4.8,
    reviewCount: 89,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera giám sát", "Sân vườn nhỏ"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 89,
      liveUpdates: false,
    },
    confidenceScore: 78,
  },
  {
    id: 5,
    name: "Tuấn Kiệt",
    type: "Nhà riêng",
    price: 180000,
    rating: 4.9,
    reviewCount: 456,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn rộng", "Dắt đi dạo miễn phí"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 456,
      liveUpdates: true,
    },
    confidenceScore: 94,
  },
  {
    id: 6,
    name: "Thanh Hà",
    type: "Căn hộ",
    price: 160000,
    rating: 4.7,
    reviewCount: 234,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 234,
      liveUpdates: false,
    },
    confidenceScore: 82,
  },
  {
    id: 7,
    name: "Hồng Quân",
    type: "Nhà riêng",
    price: 220000,
    rating: 5.0,
    reviewCount: 567,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 1 chó",
    amenities: ["Bể bơi mini", "Spa thú cưng"],
    petType: ["dog"],
    personality: ["friendly"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 567,
      liveUpdates: true,
    },
    confidenceScore: 96,
  },
  {
    id: 8,
    name: "Như Ý",
    type: "Căn hộ",
    price: 135000,
    rating: 4.6,
    reviewCount: 178,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera 24/7", "Báo cáo hàng ngày"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 178,
      liveUpdates: true,
    },
    confidenceScore: 76,
  },
  {
    id: 9,
    name: "Duy Khang",
    type: "Khách sạn thú cưng",
    price: 195000,
    rating: 4.9,
    reviewCount: 723,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 8 mèo",
    amenities: ["Phòng riêng biệt", "Khám sức khỏe định kỳ"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 723,
      liveUpdates: true,
    },
    confidenceScore: 97,
  },
  {
    id: 10,
    name: "Mai Phương",
    type: "Căn hộ",
    price: 145000,
    rating: 4.8,
    reviewCount: 201,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi thông minh"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 201,
      liveUpdates: false,
    },
    confidenceScore: 79,
  },
  {
    id: 11,
    name: "Quốc Anh",
    type: "Nhà riêng",
    price: 210000,
    rating: 5.0,
    reviewCount: 445,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân vườn lớn", "Huấn luyện cơ bản"],
    petType: ["dog"],
    personality: ["aggressive", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 445,
      liveUpdates: true,
    },
    confidenceScore: 93,
  },
  {
    id: 12,
    name: "Bảo Trâm",
    type: "Căn hộ",
    price: 155000,
    rating: 4.7,
    reviewCount: 167,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Tủ lạnh riêng"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 167,
      liveUpdates: false,
    },
    confidenceScore: 75,
  },
  {
    id: 13,
    name: "Thành Đạt",
    type: "Nhà riêng",
    price: 190000,
    rating: 4.9,
    reviewCount: 389,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 2 mèo",
    amenities: ["Cây cào móng", "Phòng chơi riêng"],
    petType: ["cat"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 389,
      liveUpdates: true,
    },
    confidenceScore: 91,
  },
  {
    id: 14,
    name: "Ngọc Lan",
    type: "Căn hộ",
    price: 140000,
    rating: 4.6,
    reviewCount: 156,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera giám sát", "Cửa sổ thoáng mát"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/home_with_cats.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 156,
      liveUpdates: false,
    },
    confidenceScore: 68,
  },
  {
    id: 15,
    name: "Văn Hoàng",
    type: "Khách sạn thú cưng",
    price: 230000,
    rating: 5.0,
    reviewCount: 892,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 12 thú cưng",
    amenities: ["Bác sĩ thú y 24/7", "Spa cao cấp"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "aggressive", "active"],
    specialNeeds: ["medical-care", "medication", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "Pet sister/istockphoto-1171217979-612x612.jpg",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 892,
      liveUpdates: true,
    },
    confidenceScore: 99,
  },
  {
    id: 16,
    name: "Thu Hương",
    type: "Căn hộ",
    price: 165000,
    rating: 4.8,
    reviewCount: 278,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ ăn organic"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["strict-diet"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 278,
      liveUpdates: true,
    },
    confidenceScore: 85,
  },
  {
    id: 17,
    name: "Minh Tuấn",
    type: "Nhà riêng",
    price: 185000,
    rating: 4.9,
    reviewCount: 534,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 1 chó",
    amenities: ["Sân tập luyện", "Đồ chơi đa dạng"],
    petType: ["dog"],
    personality: ["active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 534,
      liveUpdates: true,
    },
    confidenceScore: 95,
  },
  {
    id: 18,
    name: "Hải Yến",
    type: "Căn hộ",
    price: 130000,
    rating: 4.5,
    reviewCount: 123,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Điều Hòa"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_hotel_building.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 123,
      liveUpdates: false,
    },
    confidenceScore: 64,
  },
  {
    id: 19,
    name: "Đức Mạnh",
    type: "Nhà riêng",
    price: 205000,
    rating: 5.0,
    reviewCount: 678,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 chó",
    amenities: ["Sân vườn rộng", "Bể tắm riêng"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 678,
      liveUpdates: true,
    },
    confidenceScore: 97,
  },
  {
    id: 20,
    name: "Thùy Linh",
    type: "Căn hộ",
    price: 125000,
    rating: 4.6,
    reviewCount: 145,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Đồ chơi"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 145,
      liveUpdates: false,
    },
    confidenceScore: 65,
  },
  {
    id: 21,
    name: "Anh Tuấn",
    type: "Khách sạn thú cưng",
    price: 240000,
    rating: 5.0,
    reviewCount: 1045,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 15 thú cưng",
    amenities: ["Phòng VIP", "Bác sĩ thú y", "Spa"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "active"],
    specialNeeds: ["medical-care", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "Pet sister/Teneo-WFA-Hero-2022.jpg",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 1045,
      liveUpdates: true,
    },
    confidenceScore: 100,
  },
  {
    id: 22,
    name: "Phương Thảo",
    type: "Căn hộ",
    price: 148000,
    rating: 4.7,
    reviewCount: 189,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Camera"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 189,
      liveUpdates: false,
    },
    confidenceScore: 77,
  },
  {
    id: 23,
    name: "Tuấn Anh",
    type: "Nhà riêng",
    price: 195000,
    rating: 4.9,
    reviewCount: 423,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân chơi", "Huấn luyện"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 423,
      liveUpdates: true,
    },
    confidenceScore: 92,
  },
  {
    id: 24,
    name: "Khánh Ly",
    type: "Căn hộ",
    price: 158000,
    rating: 4.8,
    reviewCount: 267,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Cửa sổ lớn", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 267,
      liveUpdates: true,
    },
    confidenceScore: 84,
  },
  {
    id: 25,
    name: "Hoàng Long",
    type: "Nhà riêng",
    price: 215000,
    rating: 5.0,
    reviewCount: 756,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 3 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Spa"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 756,
      liveUpdates: true,
    },
    confidenceScore: 98,
  },
  {
    id: 26,
    name: "Ngọc Anh",
    type: "Căn hộ",
    price: 142000,
    rating: 4.6,
    reviewCount: 198,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 198,
      liveUpdates: false,
    },
    confidenceScore: 73,
  },
  {
    id: 27,
    name: "Quang Minh",
    type: "Khách sạn thú cưng",
    price: 188000,
    rating: 4.9,
    reviewCount: 534,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 9 mèo",
    amenities: ["Phòng riêng", "Camera 24/7"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 534,
      liveUpdates: true,
    },
    confidenceScore: 95,
  },
  {
    id: 28,
    name: "Hồng Ngọc",
    type: "Căn hộ",
    price: 137000,
    rating: 4.7,
    reviewCount: 176,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Camera"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 176,
      liveUpdates: false,
    },
    confidenceScore: 70,
  },
  {
    id: 29,
    name: "Việt Anh",
    type: "Nhà riêng",
    price: 198000,
    rating: 4.9,
    reviewCount: 467,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn", "Dắt đi dạo"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 467,
      liveUpdates: true,
    },
    confidenceScore: 94,
  },
  {
    id: 30,
    name: "Thanh Tâm",
    type: "Căn hộ",
    price: 153000,
    rating: 4.8,
    reviewCount: 223,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Cửa sổ view đẹp"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 223,
      liveUpdates: false,
    },
    confidenceScore: 81,
  },
  {
    id: 31,
    name: "Đức Thịnh",
    type: "Nhà riêng",
    price: 225000,
    rating: 5.0,
    reviewCount: 834,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 thú cưng",
    amenities: ["Sân vườn lớn", "Bác sĩ thú y"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care", "medication"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 834,
      liveUpdates: true,
    },
    confidenceScore: 99,
  },
  {
    id: 32,
    name: "Minh Châu",
    type: "Căn hộ",
    price: 143000,
    rating: 4.6,
    reviewCount: 187,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Đồ chơi"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 187,
      liveUpdates: false,
    },
    confidenceScore: 72,
  },
  {
    id: 33,
    name: "Trung Kiên",
    type: "Khách sạn thú cưng",
    price: 208000,
    rating: 4.9,
    reviewCount: 645,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 11 thú cưng",
    amenities: ["Phòng VIP", "Khám sức khỏe"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 645,
      liveUpdates: true,
    },
    confidenceScore: 97,
  },
  {
    id: 34,
    name: "Bích Ngọc",
    type: "Căn hộ",
    price: 168000,
    rating: 4.8,
    reviewCount: 289,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Máy lọc không khí"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning", "afternoon"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 289,
      liveUpdates: true,
    },
    confidenceScore: 86,
  },
  {
    id: 35,
    name: "Huy Hoàng",
    type: "Nhà riêng",
    price: 192000,
    rating: 4.9,
    reviewCount: 512,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân chơi", "Bể tắm"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 512,
      liveUpdates: true,
    },
    confidenceScore: 95,
  },
  {
    id: 36,
    name: "Lan Anh",
    type: "Căn hộ",
    price: 134000,
    rating: 4.5,
    reviewCount: 154,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Điều Hòa"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_hotel_building.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 154,
      liveUpdates: false,
    },
    confidenceScore: 62,
  },
  {
    id: 37,
    name: "Công Phượng",
    type: "Nhà riêng",
    price: 235000,
    rating: 5.0,
    reviewCount: 923,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 5 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Spa cao cấp"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image:
      "Pet sister/Labrador-retriever-sitting-on-the-couch-next-to-a-man-giving-a-high-five.jpg",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 923,
      liveUpdates: true,
    },
    confidenceScore: 100,
  },
  {
    id: 38,
    name: "Thu Trang",
    type: "Căn hộ",
    price: 147000,
    rating: 4.7,
    reviewCount: 212,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 212,
      liveUpdates: false,
    },
    confidenceScore: 80,
  },
  {
    id: 39,
    name: "Minh Quân",
    type: "Khách sạn thú cưng",
    price: 218000,
    rating: 5.0,
    reviewCount: 778,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 13 thú cưng",
    amenities: ["Bác sĩ thú y 24/7", "Phòng riêng cao cấp"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy", "aggressive", "active"],
    specialNeeds: ["medical-care", "medication", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet", "restricted-food"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 778,
      liveUpdates: true,
    },
    confidenceScore: 98,
  },
  {
    id: 40,
    name: "Hải Yến",
    type: "Căn hộ",
    price: 159000,
    rating: 4.8,
    reviewCount: 245,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Camera giám sát"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 245,
      liveUpdates: false,
    },
    confidenceScore: 83,
  },
  {
    id: 41,
    name: "Tuấn Đạt",
    type: "Nhà riêng",
    price: 202000,
    rating: 4.9,
    reviewCount: 589,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 2 chó",
    amenities: ["Sân vườn", "Huấn luyện cơ bản"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 589,
      liveUpdates: true,
    },
    confidenceScore: 96,
  },
  {
    id: 42,
    name: "Phương Linh",
    type: "Căn hộ",
    price: 138000,
    rating: 4.6,
    reviewCount: 167,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Cửa sổ lớn", "Đồ chơi"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 167,
      liveUpdates: false,
    },
    confidenceScore: 67,
  },
  {
    id: 43,
    name: "Anh Khoa",
    type: "Nhà riêng",
    price: 213000,
    rating: 5.0,
    reviewCount: 712,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 4 chó",
    amenities: ["Sân vườn rộng", "Bể bơi"],
    petType: ["dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 712,
      liveUpdates: true,
    },
    confidenceScore: 97,
  },
  {
    id: 44,
    name: "Ngọc Mai",
    type: "Căn hộ",
    price: 151000,
    rating: 4.7,
    reviewCount: 234,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Máy lọc không khí"],
    petType: ["cat"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "experienced-with-shy",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 234,
      liveUpdates: true,
    },
    confidenceScore: 79,
  },
  {
    id: 45,
    name: "Hoàng Nam",
    type: "Khách sạn thú cưng",
    price: 198000,
    rating: 4.9,
    reviewCount: 623,
    location: "Sơn Trà, Đà Nẵng",
    status: "Hiện đang giữ 10 thú cưng",
    amenities: ["Phòng riêng", "Khám sức khỏe định kỳ"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 623,
      liveUpdates: true,
    },
    confidenceScore: 96,
  },
  {
    id: 46,
    name: "Thanh Huyền",
    type: "Căn hộ",
    price: 144000,
    rating: 4.6,
    reviewCount: 198,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Camera", "Đồ chơi thông minh"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "basic",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "new",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 198,
      liveUpdates: false,
    },
    confidenceScore: 71,
  },
  {
    id: 47,
    name: "Văn Thành",
    type: "Nhà riêng",
    price: 207000,
    rating: 4.9,
    reviewCount: 556,
    location: "Cẩm Lệ, Đà Nẵng",
    status: "Hiện đang giữ 3 chó",
    amenities: ["Sân chơi", "Dắt đi dạo hàng ngày"],
    petType: ["dog"],
    personality: ["active", "aggressive"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["morning", "afternoon"],
    image: "images/home_with_cats.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 556,
      liveUpdates: true,
    },
    confidenceScore: 95,
  },
  {
    id: 48,
    name: "Kim Ngân",
    type: "Căn hộ",
    price: 162000,
    rating: 4.8,
    reviewCount: 276,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Điều Hòa", "Cây cào móng"],
    petType: ["cat"],
    personality: ["friendly"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "indoor-only",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: true,
      verifiedReviewCount: 276,
      liveUpdates: true,
    },
    confidenceScore: 85,
  },
  {
    id: 49,
    name: "Quốc Bảo",
    type: "Nhà riêng",
    price: 228000,
    rating: 5.0,
    reviewCount: 867,
    location: "Ngũ Hành Sơn, Đà Nẵng",
    status: "Hiện đang giữ 5 thú cưng",
    amenities: ["Sân vườn", "Bể bơi", "Bác sĩ thú y"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care", "senior-pet"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_sitter_poodle.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 867,
      liveUpdates: true,
    },
    confidenceScore: 99,
  },
  {
    id: 50,
    name: "Thúy Hằng",
    type: "Căn hộ",
    price: 156000,
    rating: 4.7,
    reviewCount: 223,
    location: "Thanh Khê, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Máy lọc không khí", "Camera 24/7"],
    petType: ["cat"],
    personality: ["shy"],
    specialNeeds: ["medication"],
    experienceLevel: "experienced-with-shy",
    diet: ["restricted-food"],
    environment: "indoor-only",
    availability: ["morning"],
    image: "images/home_with_cats.png",
    trustLevel: "verified",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: false,
      hasCertificate: false,
      verifiedReviewCount: 223,
      liveUpdates: false,
    },
    confidenceScore: 78,
  },
  {
    id: 51,
    name: "Bảo Trâm",
    type: "Căn hộ",
    price: 180000,
    rating: 4.8,
    reviewCount: 278,
    location: "Hải Châu, Đà Nẵng",
    status: "Sẵn sàng nhận thêm",
    amenities: ["Live cam 24/7", "Kinh nghiệm y tế", "Ban công thoáng mát"],
    petType: ["cat", "dog"],
    personality: ["friendly", "active"],
    specialNeeds: ["medical-care"],
    experienceLevel: "medical-experience",
    diet: ["normal", "strict-diet"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/pet_hotel_building.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 278,
      liveUpdates: true,
    },
    confidenceScore: 91,
  },
  {
    id: 52,
    name: "Bảo Trâm",
    type: "Nhà riêng",
    price: 160000,
    rating: 4.9,
    reviewCount: 156,
    location: "Hải Châu, Đà Nẵng",
    status: "Hiện đang giữ 2 mèo",
    amenities: ["Sân vườn rộng", "Khu vực yên tĩnh", "Chăm sóc như gia đình"],
    petType: ["cat", "dog"],
    personality: ["friendly", "shy"],
    specialNeeds: ["none"],
    experienceLevel: "professional",
    diet: ["normal"],
    environment: "can-go-outside",
    availability: ["all-day"],
    image: "images/cats_hero.png",
    trustLevel: "pro",
    verifiedDetails: {
      idCheck: true,
      backgroundCheck: true,
      hasCertificate: true,
      verifiedReviewCount: 156,
      liveUpdates: true,
    },
    confidenceScore: 93,
  },
];

// Initialize mock pets in localStorage on first load
if (!localStorage.getItem("pettel_pets")) {
  const mockPets = [
    {
      id: "min",
      name: "Min",
      species: "cat",
      sex: "male",
      age: 3,
      diet: "2× daily · No fish",
      vaccination: "Up to date · Mar 2026",
      personality: ["shy", "indoor-only"],
      specialNote:
        "Stress when meeting strangers — needs 30 min warm-up before handling",
    },
    {
      id: "mun",
      name: "Mun",
      species: "cat",
      sex: "male",
      age: 1.5,
      diet: "3× daily · Wet food only",
      vaccination: "Up to date · Jan 2026",
      personality: ["active", "shy"],
      specialNote: "Ăn nhiều, cần kiểm soát khẩu phần",
    },
  ];
  localStorage.setItem("pettel_pets", JSON.stringify(mockPets));
}

// Add district property to all sitters by parsing location
sittersData.forEach((sitter) => {
  if (sitter.location && !sitter.district) {
    // Extract district from "District, City" format
    const parts = sitter.location.split(",");
    if (parts.length > 0) {
      sitter.district = parts[0].trim().toLowerCase();
    }
  }
});

// Pet sister folder images
const petSisterImages = [
  "Pet sister/Teneo-WFA-Hero-2022.jpg",
  "Pet sister/smiling-young-asian-woman-in-yellow-shirt-is-holding-a-white-ragdoll-cat-over-isolated-white-background-photo.jpg",
  "Pet sister/Single-Services-of-Dog-Grooming_4-scaled.jpg",
  "Pet sister/R.jpg",
  "Pet sister/portrait-young-asian-woman-holding-600nw-2344067699.webp",
  "Pet sister/portrait-beautiful-chinese-young-girl-hug-her-cute-british-shorthair-cat-who-has-amazing-orange-eyes-home-sunny-afternoon-141149436.webp",
  "Pet sister/pexels-thirdman-9313652-1-1400x933.jpg",
  "Pet sister/PDP_Sticks_LifestyleImage_GuyWithDog.webp",
  "Pet sister/OIP.webp",
  "Pet sister/MV5BNTMxNzE3NDUtMjBiMy00M2U4LTg3MTctMzY1Nzk3MDg4OGJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  "Pet sister/MTXX_MR20230613_153129205_1.webp",
  "Pet sister/Labrador-retriever-sitting-on-the-couch-next-to-a-man-giving-a-high-five.jpg",
  "Pet sister/istockphoto-665117590-612x612.jpg",
  "Pet sister/istockphoto-174837615-170667a.jpg",
  "Pet sister/istockphoto-1391961103-170667a.webp",
  "Pet sister/istockphoto-1329541969-612x612.jpg",
  "Pet sister/istockphoto-1285083459-612x612.jpg",
  "Pet sister/istockphoto-1171217979-612x612.jpg",
  "Pet sister/happy-asian-woman-enjoying-her-dog-pet-home-friendship-pet-human-lifestyle-concept_1137986-1678.avif",
  "Pet sister/glenn-han-yjXXlapVYrQ-unsplash-min-1536x1024.jpg",
  "Pet sister/dv2-1249-6330.jpg",
  "Pet sister/Brunos-Play-Center-1000x750.jpg",
  "Pet sister/artworks-9OVWQIWvyNL6cJd4-vF5eqQ-t500x500.jpg",
  "Pet sister/5-ella-chen-data.jpg",
  "Pet sister/585dd8967f02af6c1982394f472cd1f5.jpg",
  "Pet sister/46e2e0_1f31434b61c34ff48d2175a16de6a09a~mv2.avif",
  "Pet sister/2-1665279330.jpg",
  "Pet sister/0d0eef1b4633a11610c34c1e1a236598.jpg",
];

// All service options
const allServices = [
  "trongtaigia",
  "guigam",
  "datdidao",
  "cattialong",
  "vesinhspa",
];

// Districts for distribution
const districts = [
  "haichau",
  "camle",
  "sontra",
  "thanhkhe",
  "lienchiều",
  "ngu hanh son",
];
const districtNames = [
  "Hải Châu",
  "Cẩm Lệ",
  "Sơn Trà",
  "Thanh Khê",
  "Liên Chiểu",
  "Ngũ Hành Sơn",
];

// Price ranges for distribution (in VND)
const priceRanges = [
  {min: 50000, max: 99000}, // 0-100k range
  {min: 100000, max: 199000}, // 100-200k range
  {min: 200000, max: 299000}, // 200-300k range
  {min: 300000, max: 399000}, // 300-400k range
  {min: 400000, max: 499000}, // 400-500k range
  {min: 500000, max: 700000}, // 500k+ range
];

// Add services, district, price, and update images for all sitters
sittersData.forEach((sitter, index) => {
  // Add services - randomly assign 2-4 services to each sitter
  if (!sitter.services) {
    const numServices = Math.floor(Math.random() * 3) + 2; // 2-4 services
    const shuffled = [...allServices].sort(() => 0.5 - Math.random());
    sitter.services = shuffled.slice(0, numServices);
  }

  // Assign district - distribute evenly with some variation
  const districtIndex = index % districts.length;
  sitter.district = districts[districtIndex];
  sitter.location = `${districtNames[districtIndex]}, Đà Nẵng`;

  // Assign price - distribute across all ranges
  const priceRangeIndex = index % priceRanges.length;
  const range = priceRanges[priceRangeIndex];
  // Random price within the range
  sitter.price =
    Math.floor(Math.random() * (range.max - range.min + 1)) + range.min;

  // Update image from Pet sister folder
  sitter.image = petSisterImages[index % petSisterImages.length];
});
